apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    name: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      name: nginx
  template:
    metadata:
      labels:
        name: nginx
    spec:
#      hostNetwork: true
      containers:
        - name: nginx
          image: nginx:1.7.9
          ports:
            - containerPort: 80
#              hostPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    name: nginx
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 31234
  selector:
    name: nginx